celestiatestnet:
  decimals: 0
  destinationGas:
    "2147483647": "0"
  hook: "0x0000000000000000000000000000000000000000"
  interchainSecurityModule: "0x0000000000000000000000000000000000000000"
  mailbox: "0x68797065726c616e650000000000000000000000000000000000000000000000"
  name: ""
  owner: celestia1lg0e9n4pt29lpq2k4ptue4ckw09dx0aujlpe4j
  remoteRouters:
    "2147483647":
      address: "0x00000000000000000000000043505da95A74Fa577FB9bB0Ce29E293FdF575011"
  symbol: ""
  token: utia
  type: collateral

