services:
  relayer:
    image: gcr.io/abacus-labs-dev/hyperlane-agent:agents-v1.7.0
    platform: linux/amd64
    container_name: hyperlane-relayer
    user: "0:0"
    volumes:
      - ./relayer/config.json:/app/config/config.json:ro
      - relayer-db:/app/hyperlane_db
    environment:
      - CONFIG_FILES=/app/config/config.json
      - HYP_CHAINS_CELESTIATESTNET_SIGNER_KEY=${HYP_CHAINS_CELESTIATESTNET_SIGNER_KEY}
      - HYP_CHAINS_EDENTESTNET_SIGNER_KEY=${HYP_CHAINS_EDENTESTNET_SIGNER_KEY}
      - HYP_CHAINS_SEPOLIA_SIGNER_KEY=${HYP_CHAINS_SEPOLIA_SIGNER_KEY}
      - HYP_CHAINS_SEPOLIA_MAILBOX=0xb58a0742AA0986eC81D28356E07612Cf23bA95b9
      - HYP_CHAINS_SEPOLIA_MERKLETREEHOOK=0x8218355F8F8d0057233dDc01DFD9E1Cb20b422A6
    ports:
      - "9090:9090"
    command: "/app/relayer"
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - hyperlane-net

volumes:
  relayer-db:

networks:
  hyperlane-net:
    driver: bridge
