site_name: hyperlane-ops
site_description: Hyperlane architecture and deployment guides for Celestia

repo_name: celestiaorg/hyperlane-ops
repo_url: https://github.com/celestiaorg/hyperlane-ops

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.sections
    - navigation.tracking
    - content.code.copy

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight
  - pymdownx.inlinehilite

plugins:
  - search

extra_javascript:
  - https://unpkg.com/beautiful-mermaid@0.1.3/dist/beautiful-mermaid.browser.global.js
  - js/beautiful-mermaid-init.js

extra_css:
  - stylesheets/extra.css

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Glossary: glossary.md
  - Core Deployments:
      - New chain Onboarding: new-chain-onboarding.md
      - Celestia: celestia-core-deploy.md
      - EVM: evm-core-deploy.md
      - Multisig ISM: multisig-ism.md
  - Warp Routes:
      - Warp Routes Guide: warp-routes.md
      - Warp Routes Multichain: warp-route-multichain.md
  - Agents:
      - Relayer: relayer.md
  - Mocha:
      - Testnet Deployments: testnet-deployments.md
  - Solidity Tooling:
      - HypNativeMinter: solidity-hypnativeminter.md
