celestiatestnet:
  decimals: 0
  destinationGas:
    "1196573006": "68000"
    "2147483647": "64000"
  hook: "0x0000000000000000000000000000000000000000"
  interchainSecurityModule: "0x0000000000000000000000000000000000000000"
  mailbox: "0x68797065726c616e650000000000000000000000000000000000000000000000"
  name: ""
  owner: celestia1lg0e9n4pt29lpq2k4ptue4ckw09dx0aujlpe4j
  remoteRouters:
    "1196573006":
      address: "0x726f757465725f61707000000000000000000000000000010000000000000008"
    "2147483647":
      address: "0x000000000000000000000000e1141469cff3db185a0e1b9ebd1d31bb22a623ea"
  symbol: ""
  type: synthetic
