nobletestnet:
  decimals: 0
  destinationGas:
    "1297040200": "64000"
  hook: "0x0000000000000000000000000000000000000000"
  interchainSecurityModule: "0x0000000000000000000000000000000000000000"
  mailbox: "0x68797065726c616e650000000000000000000000000000000000000000000000"
  name: ""
  owner: noble1lg0e9n4pt29lpq2k4ptue4ckw09dx0autk9ph3
  remoteRouters:
    "1297040200":
      address: "0x726f757465725f61707000000000000000000000000000020000000000000015"
  symbol: ""
  token: uusdc
  type: collateral

