defaultHook:
  beneficiary: "0xc259e540167B7487A89b45343F4044d5951cf871"
  maxProtocolFee: "0"
  owner: "0xc259e540167B7487A89b45343F4044d5951cf871"
  protocolFee: "0"
  type: protocolFee
defaultIsm:
  type: testIsm
owner: "0xc259e540167B7487A89b45343F4044d5951cf871"
proxyAdmin:
  owner: "0xc259e540167B7487A89b45343F4044d5951cf871"
requiredHook:
  type: merkleTreeHook

