defaultHook:
  address: "0x726f757465725f706f73745f6469737061746368000000000000000000000004"
  owner: celestia1lg0e9n4pt29lpq2k4ptue4ckw09dx0aujlpe4j
  type: noopHook # Unsupported by the CLI, currently errors when trying to read this configuration from on-chain state
defaultIsm:
  address: "0x726f757465725f69736d00000000000000000000000000010000000000000000"
  domains:
    xomarket:
      address: "0x726f757465725f69736d0000000000000000000000000000000000000000000d"
      type: testIsm
  owner: celestia1lg0e9n4pt29lpq2k4ptue4ckw09dx0aujlpe4j
  type: domainRoutingIsm
owner: celestia1lg0e9n4pt29lpq2k4ptue4ckw09dx0aujlpe4j
requiredHook:
  address: "0x726f757465725f706f73745f6469737061746368000000030000000000000000"
  type: merkleTreeHook
