celestiatestnet:
  decimals: 0
  destinationGas:
    "11155111": "68000"
    "2147483647": "64000"
  hook: "0x0000000000000000000000000000000000000000"
  interchainSecurityModule: "0x0000000000000000000000000000000000000000"
  mailbox: "0x68797065726c616e650000000000000000000000000000000000000000000000"
  name: ""
  owner: celestia1lg0e9n4pt29lpq2k4ptue4ckw09dx0aujlpe4j
  remoteRouters:
    "11155111":
      address: "0x000000000000000000000000101612e45d8d1ebe8e2eb90373b7ccecb6f52f5c"
    "2147483647":
      address: "0x0000000000000000000000004d46424a8aa50e7c585f218338bcce4a9a992c0f"
  symbol: ""
  type: synthetic

